export const BUSINESSES = [
  {
    id: "1",
    name: "Acme Plumbing Co.",
    tagline: "Leak Diagnosis & Repair",
    category: "Plumbing",
    price: 95,
    mode: "In-person",
    rating: 4.8,
    reviewCount: 128,
    location: "Waterloo, ON",
    about:
      "Acme Plumbing Co. has been serving Waterloo and surrounding neighbourhoods since 2009. We specialize in residential and light commercial plumbing repairs, installations, and emergency services. All work is fully licensed and insured.",
    fromPrice: 95,
    priceUnit: "visit",
    nextAvailable: "Tomorrow · 9:00 AM",
    hoursToday: "Open until 6 PM",
    phone: "(519) 555-0101",
    services: [
      { name: "Leak diagnosis & repair", duration: "45 min", price: "$95" },
      { name: "Drain cleaning", duration: "1 hr", price: "$140" },
      { name: "Water heater install", duration: "2–3 hrs", price: "$420+" },
      { name: "Pipe replacement", duration: "3–5 hrs", price: "$600+" },
      { name: "Toilet repair", duration: "30 min", price: "$75" },
    ],
    reviews: [
      { author: "Sarah K.", rating: 5, date: "May 2026", body: "Fixed our leak in under an hour. Price was exactly as quoted." },
      { author: "Mike R.", rating: 5, date: "Apr 2026", body: "Professional, punctual, and fair pricing. Would definitely book again." },
      { author: "Lisa M.", rating: 4, date: "Mar 2026", body: "Good work overall. Arrived on time and explained everything clearly." },
    ],
  },
  {
    id: "2",
    name: "Pawsh Pet Salon",
    tagline: "Full Pet Grooming",
    category: "Pet grooming",
    price: 75,
    mode: "In-person",
    rating: 4.7,
    reviewCount: 84,
    location: "Kitchener, ON",
    about:
      "Pawsh Pet Salon offers premium grooming for dogs and cats of all breeds. Our certified groomers treat every pet with care and patience in a stress-free environment.",
    fromPrice: 75,
    priceUnit: "session",
    nextAvailable: "Today · 3:00 PM",
    hoursToday: "Open until 7 PM",
    phone: "(519) 555-0202",
    services: [
      { name: "Full groom (small dog)", duration: "1 hr", price: "$75" },
      { name: "Full groom (large dog)", duration: "2 hrs", price: "$110" },
      { name: "Bath & brush", duration: "45 min", price: "$50" },
      { name: "Nail trim", duration: "15 min", price: "$20" },
      { name: "Cat grooming", duration: "1.5 hrs", price: "$85" },
    ],
    reviews: [
      { author: "Jamie L.", rating: 5, date: "Jun 2026", body: "My golden retriever looks amazing. The staff are so gentle and kind." },
      { author: "Priya S.", rating: 4, date: "May 2026", body: "Great experience overall. My pup was relaxed the whole time." },
      { author: "Dan M.", rating: 5, date: "Apr 2026", body: "Best groomer in Kitchener. Highly recommend!" },
    ],
  },
  {
    id: "3",
    name: "Sparkle Home Services",
    tagline: "Home Cleaning",
    category: "Cleaning",
    price: 120,
    mode: "In-person",
    rating: 4.6,
    reviewCount: 211,
    location: "Waterloo, ON",
    about:
      "Sparkle Home Services provides thorough, reliable cleaning for homes and apartments across Waterloo. We use eco-friendly products and customizable cleaning plans to fit your schedule.",
    fromPrice: 120,
    priceUnit: "visit",
    nextAvailable: "Tomorrow · 10:00 AM",
    hoursToday: "Open until 5 PM",
    phone: "(519) 555-0303",
    services: [
      { name: "Standard clean", duration: "2 hrs", price: "$120" },
      { name: "Deep clean", duration: "4 hrs", price: "$220" },
      { name: "Move-in / move-out clean", duration: "5–6 hrs", price: "$300+" },
      { name: "Recurring bi-weekly", duration: "2 hrs", price: "$100/visit" },
      { name: "Fridge & oven add-on", duration: "+30 min", price: "$40" },
    ],
    reviews: [
      { author: "Rachel T.", rating: 5, date: "Jun 2026", body: "Our apartment was spotless. They even cleaned behind the fridge!" },
      { author: "Carlos N.", rating: 4, date: "May 2026", body: "Reliable and thorough. A little late but communicated ahead of time." },
      { author: "Anna B.", rating: 5, date: "Apr 2026", body: "I've used Sparkle 4 times now. Consistent quality every single time." },
    ],
  },
  {
    id: "4",
    name: "BrightPath Tutors",
    tagline: "Math Tutoring",
    category: "Tutoring",
    price: 40,
    mode: "Online",
    rating: 4.9,
    reviewCount: 63,
    location: "Online",
    about:
      "BrightPath Tutors connects students with experienced educators for one-on-one academic support. We specialize in math, sciences, and standardized test prep for grades 6–12.",
    fromPrice: 40,
    priceUnit: "hour",
    nextAvailable: "Today · 5:00 PM",
    hoursToday: "Available until 9 PM",
    phone: "(519) 555-0404",
    services: [
      { name: "Math tutoring", duration: "1 hr", price: "$40" },
      { name: "Science tutoring", duration: "1 hr", price: "$40" },
      { name: "SAT / ACT prep", duration: "1.5 hrs", price: "$65" },
      { name: "Essay writing support", duration: "1 hr", price: "$45" },
      { name: "5-session bundle", duration: "5 × 1 hr", price: "$175" },
    ],
    reviews: [
      { author: "Yuki T.", rating: 5, date: "Jun 2026", body: "My daughter went from a C to an A in math after just 4 sessions. Amazing!" },
      { author: "Omar F.", rating: 5, date: "May 2026", body: "Incredibly patient and clear explanations. Best tutor we've found online." },
      { author: "Helen W.", rating: 5, date: "Mar 2026", body: "Very structured sessions. My son actually looks forward to them now." },
    ],
  },
  {
    id: "5",
    name: "Frame Studio",
    tagline: "Portrait Photography",
    category: "Photography",
    price: 150,
    mode: "In-person",
    rating: 4.5,
    reviewCount: 47,
    location: "Waterloo, ON",
    about:
      "Frame Studio specializes in portrait, event, and product photography in Waterloo. We deliver edited galleries within 5 business days and offer flexible booking for shoots of any size.",
    fromPrice: 150,
    priceUnit: "session",
    nextAvailable: "Sat · 11:00 AM",
    hoursToday: "Open until 6 PM",
    phone: "(519) 555-0505",
    services: [
      { name: "Portrait session", duration: "1 hr", price: "$150" },
      { name: "Family shoot", duration: "1.5 hrs", price: "$225" },
      { name: "Headshots", duration: "30 min", price: "$99" },
      { name: "Event photography", duration: "3 hrs", price: "$450" },
      { name: "Product photography", duration: "2 hrs", price: "$280" },
    ],
    reviews: [
      { author: "Bree O.", rating: 5, date: "May 2026", body: "Our family photos turned out stunning. Super easy to work with." },
      { author: "Kevin P.", rating: 4, date: "Apr 2026", body: "Great headshots, quick turnaround. Would book again for events." },
      { author: "Suki L.", rating: 5, date: "Feb 2026", body: "Product shots were exactly what I needed for my Shopify store." },
    ],
  },
  {
    id: "6",
    name: "FitLife Coaching",
    tagline: "Personal Training Session",
    category: "Fitness Training",
    price: 60,
    mode: "Hybrid",
    rating: 4.7,
    reviewCount: 92,
    location: "Kitchener, ON",
    about:
      "FitLife Coaching offers personalized fitness programs for all levels — from beginners to competitive athletes. Sessions are available in-person at our Kitchener studio or via video call.",
    fromPrice: 60,
    priceUnit: "session",
    nextAvailable: "Tomorrow · 7:00 AM",
    hoursToday: "Open until 8 PM",
    phone: "(519) 555-0606",
    services: [
      { name: "Personal training session", duration: "1 hr", price: "$60" },
      { name: "Nutrition consultation", duration: "45 min", price: "$80" },
      { name: "10-session package", duration: "10 × 1 hr", price: "$550" },
      { name: "Online coaching (monthly)", duration: "Ongoing", price: "$120/mo" },
      { name: "Group bootcamp class", duration: "45 min", price: "$20" },
    ],
    reviews: [
      { author: "Marcus D.", rating: 5, date: "Jun 2026", body: "Lost 12 lbs in 2 months. The program was tough but so worth it." },
      { author: "Tina R.", rating: 5, date: "Apr 2026", body: "My trainer really listens and adjusts the workouts to my pace." },
      { author: "Joel C.", rating: 4, date: "Mar 2026", body: "Great sessions. Scheduling is easy and the studio is clean." },
    ],
  },
];
